# https://github.com/Fallenbagel/jellyseerr/releases
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.1
    container_name: jellyseerr
    hostname: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${DATA_DIR}/jellyseerr:/app/config"
    restart: unless-stopped
    networks:
      - jellyseerr
      - jellyfin
      - sonarr
      - radarr
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyseerr.rule=Host("jellyseerr.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.services.jellyseerr-websecure.loadbalancer.server.port=5055"
      - 'traefik.docker.network=jellyseerr'

networks:
  jellyseerr:
    external: true
  sonarr:
    external: true
  radarr:
    external: true
  jellyfin:
    external: true
