services:
  romm:
    image: rommapp/romm:4.0.0
    container_name: romm
    hostname: romm
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/romm.env"
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm-user
      - HASHEOUS_API_ENABLED=true # I try to keep my library tidy.
    volumes:
      - "${DATA_DIR}/romm/resources:/romm/resources"  # Resources fetched from IGDB (covers, screenshots, etc.)
      - "${DATA_DIR}/romm/redis:/redis-data"          # Cached data for background tasks
      - "${DATA_DIR}/romm/assets:/romm/assets"        # Uploaded saves, states, etc.
      - "${DATA_DIR}/romm/config:/romm/config"        # configuration
      # The library. I don't need everything exposed.
      - "${EMULATION_DIR}/bios:/romm/library/bios:ro"
      - "${EMULATION_DIR}/roms/gb:/romm/library/roms/gb:ro"
      - "${EMULATION_DIR}/roms/gba:/romm/library/roms/gba:ro"
      - "${EMULATION_DIR}/roms/gbc:/romm/library/roms/gbc:ro"
      - "${EMULATION_DIR}/roms/dos:/romm/library/roms/dos:ro"
      - "${EMULATION_DIR}/roms/dreamcast:/romm/library/roms/dreamcast:ro"
      - "${EMULATION_DIR}/roms/fbneo:/romm/library/roms/fbneo:ro"
      - "${EMULATION_DIR}/roms/megadrive:/romm/library/roms/megadrive:ro"
      - "${EMULATION_DIR}/roms/n64:/romm/library/roms/n64:ro"
      - "${EMULATION_DIR}/roms/nds:/romm/library/roms/nds:ro"
      - "${EMULATION_DIR}/roms/nes:/romm/library/roms/nes:ro"
      - "${EMULATION_DIR}/roms/psp:/romm/library/roms/psp:ro"
      - "${EMULATION_DIR}/roms/psx:/romm/library/roms/psx:ro"
      - "${EMULATION_DIR}/roms/snes:/romm/library/roms/snes:ro"
    depends_on:
      - romm-db
    networks:
      - romm-internal
      - romm
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.romm.rule=Host("romm.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.romm.entrypoints=websecure"
      - "traefik.http.services.romm-websecure.loadbalancer.server.port=8080"
      - 'traefik.docker.network=romm'
      # EmulatorJS specific settings: https://emulatorjs.org/docs/options#ejs_threads
      - "traefik.http.middlewares.emulatorjs-sharedarraybuffer.headers.customrequestheaders[0].Cross-Origin-Resource-Policy=cross-origin"
      - "traefik.http.middlewares.emulatorjs-sharedarraybuffer.headers.customrequestheaders[1].Cross-Origin-Embedder-Policy=require-corp"
      - "traefik.http.routers.romm.middlewares=emulatorjs-sharedarraybuffer@docker"


  romm-db:
    image: mariadb:latest
    user: "${PUID}:${PGID}"
    container_name: romm-db
    hostname: romm-db
    restart: unless-stopped
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/romm.env"
    environment:
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
    volumes:
      - "${DATA_DIR}/romm/mysql:/var/lib/mysql"
    networks:
      - romm-internal

networks:
  romm-internal:
    external: true
  romm:
    external: true
