# Bookmark manager: https://github.com/sissbruecker/linkding/releases
services:
  linkding:
    image: sissbruecker/linkding:1.41.0
    container_name: linkding
    hostname: linkding
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/linkding.env"
    environment:
      LD_SUPERUSER_NAME: bphenriques
    volumes:
      - "${DATA_DIR}/linkding:/etc/linkding/data"
    restart: unless-stopped
    networks:
      - linkding
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.linkding.rule=Host("linkding.${HOME_SERVER_CNAME}")'
      - "traefik.http.services.linkding-websecure.loadbalancer.server.port=9090"
      - 'traefik.docker.network=linkding'

networks:
  linkding:
    external: true
