# Bookmark manager: https://github.com/sissbruecker/linkding/releases
services:
  linkding:
    image: sissbruecker/linkding:1.41.0
    container_name: linkding
    hostname: linkding
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/linkding.env"
    environment:
      LD_SUPERUSER_NAME: bphenriques

      # OIDC
      LD_ENABLE_OIDC: True
      OIDC_OP_AUTHORIZATION_ENDPOINT: "https://pocket-id.${HOME_SERVER_BASE_URL}/authorize"
      OIDC_OP_TOKEN_ENDPOINT: "https://pocket-id.${HOME_SERVER_BASE_URL}/api/oidc/token"
      OIDC_OP_USER_ENDPOINT: "https://pocket-id.${HOME_SERVER_BASE_URL}/api/oidc/userinfo"
      OIDC_OP_JWKS_ENDPOINT: "https://pocket-id.${HOME_SERVER_BASE_URL}/.well-known/jwks.json"
      OIDC_USERNAME_CLAIM: preferred_username

    volumes:
      - "${DATA_DIR}/linkding:/etc/linkding/data"
    restart: unless-stopped
    networks:
      - linkding
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.linkding.rule=Host("linkding.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.linkding.entrypoints=websecure"
      - "traefik.http.services.linkding-websecure.loadbalancer.server.port=9090"
      - 'traefik.docker.network=linkding'

networks:
  linkding:
    external: true
