secrets:
  rustic_repository_password:
    file: "${HOME_SERVER_SECRETS_DIR}/backup-backblaze/repository_password.secret"

services:
 backup-backblaze:
    image: ghcr.io/rustic-rs/rustic:v0.10.0
    container_name: backup-backblaze
    hostname: backup-backblaze
    restart: unless-stopped
    secrets:
      - "rustic_repository_password"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/backup-backblaze/backblaze.env"
    environment:
      RUSTIC_CACHE_DIR: "/data/.cache"
    volumes:
      - "${DATA_DIR}/backup-backblaze/cache:/data/.cache"
      - "./rustic.toml:/etc/rustic/rustic.toml:ro"

      # Files to backup mounted under `/data/target-backup`
      - "${BPHENRIQUES_DOCUMENTS}:/data/target-backup/documents"
      - "${BPHENRIQUES_PHONE_BACKUP}:/data/target-backup/bphenriques-phone-backup"
      - "${BPHENRIQUES_NOTES}:/data/target-backup/bphenriques-notes"
      - "${BPHENRIQUES_PRIVATE}:/data/target-backup/bphenriques-notes"
      - "${RUSTIC_BACKUP_EXTRA_FILES}:/data/target-backup/extra-files"
