services:
  server:
    image: gitea/gitea:1.24.5
    container_name: gitea
    restart: unless-stopped
    hostname: gitea
    environment:
      USER_UID: "${PUID}"
      USER_GID: "${PGID}"
      # Use different port to avoid conflicting with host's ssh port.
      GITEA__server__START_SSH_SERVER: true
      GITEA__server__SSH_PORT: 222
    volumes:
      - "${DATA_DIR}/gitea:/data"
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host("gitea.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.services.gitea-websecure.loadbalancer.server.port=3000"

      # host resolving doesn't work for ssh, so you can only use "*"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=222"

      - 'traefik.docker.network=gitea'
networks:
  gitea:
    external: true
