services:
  server:
    image: gitea/gitea:1.24.2
    container_name: gitea
    restart: unless-stopped
    hostname: gitea
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    volumes:
      - "${DATA_DIR}/gitea:/data"
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host("gitea.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.services.gitea-websecure.loadbalancer.server.port=3000"
      - 'traefik.docker.network=gitea'
networks:
  gitea:
    external: true
