# https://github.com/Stirling-Tools/Stirling-PDF/releases
services:
  s-pdf:
    image: stirlingtools/stirling-pdf:1.0.2
    container_name: s-pdf
    hostname: s-pdf
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/s-pdf.env"
    environment:
      SECURITY_ENABLELOGIN: true
      SECURITY_OAUTH2_ENABLED: true
      SECURITY_OAUTH2_AUTOCREATEUSER: false
      SECURITY_OAUTH2_ISSUER: https://pocket-id.${HOME_SERVER_BASE_URL}
      SECURITY_OAUTH2_BLOCKREGISTRATION: false
      SECURITY_OAUTH2_SCOPES: "openid, profile, email"
      SECURITY_OAUTH2_USEASUSERNAME: preferred_username
      SECURITY_OAUTH2_PROVIDER: "pocket-id"
    restart: unless-stopped
    volumes:
      - "${DATA_DIR}/stirling-pdf/configs:/configs"
      - "${DATA_DIR}/stirling-pdf/custom-files:/customFiles"
      - "${DATA_DIR}/stirling-pdf/logs:/logs"
      - "./config/training-data-ocr:/usr/share/tesseract-ocr/5/tessdata"
    networks:
      - s-pdf
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.spdf.rule=Host("pdf.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.spdf.entrypoints=websecure"
      - "traefik.http.services.spdf-websecure.loadbalancer.server.port=8080"
      - 'traefik.docker.network=s-pdf'

networks:
  s-pdf:
    external: true
