services:
  couchdb:
    image: couchdb:3.5.0
    container_name: obsidian-livesync-couchdb
    hostname: obsidian-livesync-couchdb
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/obsidian-livesync.env"
    volumes:
      - "./config/local.ini:/opt/couchdb/etc/local.ini"
      - "${DATA_DIR}/obsidian-livesync/couchdb/data:/opt/couchdb/data"
      - "${DATA_DIR}/obsidian-livesync/couchdb/etc:/opt/couchdb/etc/local.d"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      COUCHDB_USER: admin
    networks:
      - obsidian-livesync
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.obsidian-livesync.rule=Host("obsidian-livesync.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.obsidian-livesync.entrypoints=websecure"
      - "traefik.http.services.obsidian-livesync-websecure.loadbalancer.server.port=5984"
      - 'traefik.docker.network=obsidian-livesync'
      # CORS setup as documented in here: https://github.com/vrtmrz/obsidian-livesync/blob/5d24c3b984e403e87f067df99cdea0a73f86134a/docs/setup_own_server.md#traefik
      - "traefik.http.routers.obsidian-livesync.middlewares=obsidiancors"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"

networks:
  obsidian-livesync:
    external: true
