services:
  komga:
    image: gotson/komga:1.22.0
    hostname: komga
    user: "${PUID}:${PGID}"
    container_name: komga
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - "${DATA_DIR}/komga/config:/config"
      - "${BOOKS_DIR}:/data/books"
      - "${COMICS_DIR}:/data/comics"
    networks:
      - komga
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.komga.rule=Host("komga.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.komga.entrypoints=websecure"
      - "traefik.http.services.komga-websecure.loadbalancer.server.port=25600"
      - 'traefik.docker.network=komga'

networks:
  komga:
    external: true

# TODO: https://komga.org/docs/installation/oauth2
# SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_POCKETID_CLIENT_ID=
# SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_POCKETID_CLIENT_SECRET=
# SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_POCKETID_CLIENT_NAME="Pocket ID"
# SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_POCKETID_CLIENT_SCOPE="openid,email,profile"
# SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_POCKETID_CLIENT_SCOPE="openid,email,profile"
