services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl="http://jellyfin.${HOME_SERVER_BASE_URL}"
    volumes:
      - "${DATA_DIR}/jellyfin:/config"
      - "${MOVIES_DIR}:/data/movies"
      - "${TV_SHOWS_DIR}:/data/tvshows"
      - "${MUSIC_DIR}:/data/music:ro"
    networks:
      - jellyfin
    labels:
      # TODO: Review the docs: https://jellyfin.org/docs/general/post-install/networking/reverse-proxy/traefik
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.rule=Host("jellyfin.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.services.jellyfin-websecure.loadbalancer.server.port=8096"
      - 'traefik.docker.network=jellyfin'

networks:
  jellyfin:
    external: true
