# Documentation: https://gethomepage.dev/v0.8.3/configs/settings/
title: Home
language: en-GB

# Theme
background: /images/background.png
favicon: /images/favicon.ico
theme: dark
color: stone
statusStyle: dot
headerStyle: clean
hideVersion: true

# Layout
layout:
  Media:
    tab: Media
    style: row
    columns: 4
    header: false
    useEqualHeights: true
  Admin:
    tab: Admin
    style: column
    columns: 4
    header: false

# Behaviour
target: _self # Use _blank to open links in a new tab, _self to open links in the same tab, and _top to open links in a new window.
logpath: /tmp # Allows the config directory being readonly.
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
