# https://github.com/miniflux/v2/releases
services:
  miniflux:
    image: miniflux/miniflux:2.2.10
    container_name: miniflux
    hostname: miniflux
    user: "${PUID}:${PGID}"
    depends_on:
      miniflux-db:
        condition: service_healthy
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/miniflux.env"
    environment:
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - BASE_URL=https://miniflux.${HOME_SERVER_BASE_URL}
    restart: unless-stopped
    networks:
      - miniflux-private
      - miniflux
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.miniflux.rule=Host("miniflux.${HOME_SERVER_CNAME}")'
      - "traefik.http.services.miniflux-websecure.loadbalancer.server.port=8080"
      - 'traefik.docker.network=miniflux'

  miniflux-db:
    image: postgres:15
    container_name: miniflux-db
    hostname: miniflux-db
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/miniflux.env"
    volumes:
      - "${DATA_DIR}/miniflux-db:/var/lib/postgresql/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - miniflux-private

networks:
  miniflux-private:
    name: miniflux-private
  miniflux:
    external: true
