# https://github.com/gethomepage/homepage/releases/
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.3.2
    container_name: homepage
    restart: unless-stopped
    hostname: homepage
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/homepage.env"
    environment:
      - "HOMEPAGE_VAR_BASE_URL=${HOME_SERVER_BASE_URL}"
      - "HOMEPAGE_VAR_SERVER_CNAME=${HOME_SERVER_CNAME}"
      - HOMEPAGE_ALLOWED_HOSTS=*
      - LOG_TARGETS=stdout
      - PUID="$PUID"
      - PGID="$PGID"
    volumes:
      - ./config:/app/config:ro
      - ./public/images:/app/public/images:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage.rule=Host(`${HOME_SERVER_CNAME}`) || Host(`www.${HOME_SERVER_CNAME}`)'
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.services.homepage-websecure.loadbalancer.server.port=3000"
      - 'traefik.docker.network=homepage'
    networks:
      - homepage

networks:
  homepage:
    external: true
