services:
  rustic-dropbox:
    image: ghcr.io/rustic-rs/rustic:v0.9.5
    container_name: rustic-dropbox
    hostname: rustic-dropbox
    restart: unless-stopped
    # user: "${PUID}:${PGID}"
    environment:
      RUSTIC_CACHE_DIR: "/data/.cache"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/rustic-dropbox.env"
    volumes:
      - "./dropbox.toml:/etc/rustic/rustic.toml:ro"
      - "${HOME_SERVER_SECRETS_DIR}/rustic-dropbox.toml:/etc/rustic/secrets.toml"
      - "${DATA_DIR}/rustic/cache:/data/.cache"
      # Files to backup
      - "${BPHENRIQUES_DOCUMENTS}:/data/target-backup/documents"
      - "${BPHENRIQUES_DOCUMENTS_CONSUME}:/data/target-backup/documents-consume"
      - "${RUSTIC_BACKUP_EXTRA_FILES}:/data/target-backup/extra-files"

# TODO: check permissions. Set a directory inside to export. Then use docker cp


