[global]
use-profiles = ["secrets"]

[repository]
repository = "opendal:dropbox"

[backup]
tags = ["documents"]

[[backup.snapshots]]
sources = [ "/data/target-backup" ]

[forget]
prune = true
keep-last = 5
keep-daily = 7
keep-weekly = 5
keep-monthly = 12
keep-yearly = 75