# Synology already owns ports 80 (routing to 5000) and 443 (routing to 5001), therefore we had to use different ports.
services:
  caddy:
    build: .
    image: custom-caddy:latest
    restart: unless-stopped
    container_name: caddy
    hostname: caddy
    user: "${PUID}:${PGID}"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/caddy.env"
    environment:
      - HOME_SERVER_CNAME=${HOME_SERVER_CNAME}
    ports:
      - "8482:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./Caddyfile.${HOME_SERVER_ENV}:/etc/caddy/Caddyfile:ro
      - "${DATA_DIR}/caddy:/data"
      - "${DATA_DIR}/caddy:/config"   # Not using read-only volumes due to permissions
    networks:
      - caddy
      - homepage
      - s-pdf
      - transmission
      - miniflux
      - prowlarr
      - sonarr
      - radarr
      - bazarr
      - jellyfin
      - jellyseerr
      - immich
      - linkding
      - paperless
      - romm
      - komga
      - gitea
      - kitchenowl
      - tandoor-public

networks:
  caddy:
    external: true
  jellyfin:
    external: true
  homepage:
    external: true
  s-pdf:
    external: true
  transmission:
    external: true
  miniflux:
    external: true
  prowlarr:
    external: true
  sonarr:
    external: true
  radarr:
    external: true
  bazarr:
    external: true
  jellyseerr:
    external: true
  immich:
    external: true
  linkding:
    external: true
  mylar3:
    external: true
  paperless:
    external: true
  romm:
    external: true
  readarr:
    external: true
  komga:
    external: true
  hoarder:
    external: true
  gitea:
    external: true
  kitchenowl:
    external: true
  tandoor-public:
    external: true
