# Shared *rr tool to manager indexers, trackers and notifications.
# https://github.com/Prowlarr/Prowlarr/releases
# https://docs.linuxserver.io/images/docker-prowlarr/
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${DATA_DIR}/prowlarr:/config"
    restart: unless-stopped
    networks:
      - prowlarr
      - sonarr
      - radarr
      - readarr
      - mylar3
      - transmission
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prowlarr.rule=Host("prowlarr.${HOME_SERVER_CNAME}")'
      - "traefik.http.services.prowlarr-websecure.loadbalancer.server.port=9696"
      - 'traefik.docker.network=prowlarr'

networks:
  prowlarr:
    name: prowlarr
    external: true
  sonarr:
    name: sonarr
    external: true
  radarr:
    name: radarr
    external: true
  transmission:
    name: transmission
    external: true
  readarr:
    name: readarr
    external: true
  mylar3:
    name: mylar3
    external: true



