[global]
use-profiles = ["secrets"]

[repository]
repository = "opendal:b2"
password-file = "/run/secrets/backblaze_rustic_repository_password"

[backup]
exclude-if-present = [ ".nobackup" ]
git-ignore = true
glob-files = [ "/data/glob.txt" ] 

[[backup.snapshots]]
sources = [ "/data/target-backup" ]

[forget]
prune = true
keep-daily = 7
keep-weekly = 5
keep-monthly = 12
keep-yearly = 2
