[global]
use-profiles = ["secrets"]

[repository]
repository = "opendal:b2"
password-file = "/run/secrets/backblaze_rustic_repository_password"

[backup]
exclude-if-present = [ ".nobackup" ]
git-ignore = true
glob-files = [ "/data/glob.txt" ] 

[[backup.snapshots]]
sources = [ "/data/target-backup" ]

[forget]
prune = true

keep-within-daily = "7 days"
keep-within-weekly = "1 month"
keep-within-monthly = "1 year"
keep-within-yearly = "2 years"
