name: rustic

secrets:
  backblaze_rustic_repository_password:
    file: "${HOME_SERVER_SECRETS_DIR}/rustic/backblaze_repository_password.secret"
  dropbox_rustic_repository_password:
    file: "${HOME_SERVER_SECRETS_DIR}/rustic/dropbox_repository_password.secret"

services:
  backblaze:
    image: ghcr.io/rustic-rs/rustic:v0.10.3
    container_name: backblaze
    hostname: backblaze
    secrets:
      - "backblaze_rustic_repository_password"
    environment:
      RUSTIC_CACHE_DIR: "/data/.cache"
      RUSTIC_LOG_LEVEL: info
    volumes:
      - "${DATA_DIR}/rustic/backblaze/cache:/data/.cache"
      - "./backblaze.toml:/etc/rustic/rustic.toml:ro"
      - "${HOME_SERVER_SECRETS_DIR}/rustic/backblaze.toml:/etc/rustic/secrets.toml:ro"
      - "./glob.txt:/data/glob.txt:ro"

      # Files to backup mounted under `/data/target-backup`
      - "${BPHENRIQUES_BACKUPS}:/data/target-backup/bphenriques-backups:ro"
      - "${BPHENRIQUES_NOTES}:/data/target-backup/bphenriques-notes:ro"
      - "${BPHENRIQUES_PRIVATE}:/data/target-backup/bphenriques-notes:ro"
      - "${RUSTIC_BACKUP_EXTRA_FILES}:/data/target-backup/extra-files:ro"
      - "${EMULATION_DIR}:/data/target-backup/emulation:ro"
      - "${MUSIC_DIR}:/data/target-backup/music:ro"
      - "${BPHENRIQUES_DOCUMENTS}:/data/target-backup/bphenriques-documents:ro"
      - "${BPHENRIQUES_PHOTOS_LIBRARY}:/data/target-backup/bphenriques-photos:ro"
      - "${BPHENRIQUES_PHOTOS_INBOX}:/data/target-backup/bphenriques-photos-inbox:ro"
      
