# Subtitles Manager: https://github.com/morpheus65535/bazarr/releases
#
# Setup links:
# - https://wiki.bazarr.media/bazarr-stats/
# - https://wiki.bazarr.media/Additional-Configuration/Performance-Tuning/
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${DATA_DIR}/bazarr:/config"
      - "${MOVIES_DIR}:/data/movies"
      - "${TV_SHOWS_DIR}:/data/tv"
    restart: unless-stopped
    networks:
      - bazarr
      - sonarr
      - radarr

networks:
  bazarr:
    external: true
  sonarr:
    external: true
  radarr:
    external: true
