services:
  web_recipes:
    image: vabene1111/recipes:2.3.3
    restart: unless-stopped
    container_name: tandoor-web
    hostname: tandoor-web
    #user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - "ALLOWED_HOSTS=tandoor.${HOME_SERVER_CNAME}"
      # Fixes images now showing up
      #- MEDIA_URL=https://tandoor.${HOME_SERVER_CNAME}/media/
      #- GUNICORN_MEDIA=1
      # OIDC
      - SOCIAL_PROVIDERS=allauth.socialaccount.providers.openid_connect
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/tandoor-recipes.env"
    volumes:
      - "${DATA_DIR}/tandoor-recipes/web/staticfiles:/opt/recipes/staticfiles"
      - "${DATA_DIR}/tandoor-recipes/web/mediafiles:/opt/recipes/mediafiles"
    depends_on:
      - db_recipes
    networks:
      - tandoor-private
      - tandoor-public
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tandoor.rule=Host("tandoor.${HOME_SERVER_CNAME}")'
      - "traefik.http.routers.tandoor.entrypoints=websecure"
      - "traefik.http.services.tandoor-websecure.loadbalancer.server.port=80"
      - 'traefik.docker.network=tandoor-public'

  db_recipes:
    image: postgres:16-alpine
    container_name: tandoor-db
    hostname: tandoor-db
    user: "${PUID}:${PGID}"
    volumes:
      - "${DATA_DIR}/tandoor-recipes/db:/var/lib/postgresql/data"
    env_file:
      - "${HOME_SERVER_SECRETS_DIR}/tandoor-recipes.env"
    restart: unless-stopped
    networks:
      - tandoor-private

networks:
  tandoor-private:
    external: true
  tandoor-public:
    external: true
